// Command genweights writes weights.gen.go: the rate-limit cost of every
// root-mount operation in the pinned spec, read from its
// x-nexus-rate-limit-weight, x-nexus-rate-limit-weight-formula and
// x-nexus-rate-limit-class markers. Absence of a weight marker means weight 1,
// as the spec says.
//
// Usage: genweights <spec URL> <output file>
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// formula is the one shape of x-nexus-rate-limit-weight-formula the transport
// implements. Any other fails generation rather than being paced wrongly.
var formula = regexp.MustCompile(`^(\d+) \+ floor\(order_count / (\d+)\)$`)

var methods = []string{"get", "put", "post", "patch", "delete"}

func main() {
	log.SetFlags(0)
	if len(os.Args) != 3 {
		log.Fatal("usage: genweights <spec URL> <output file>")
	}
	resp, err := http.Get(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("GET %s: %s", os.Args[1], resp.Status)
	}
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	var spec struct {
		Paths map[string]map[string]json.RawMessage `json:"paths"`
	}
	if err := json.Unmarshal(raw, &spec); err != nil {
		log.Fatal(err)
	}

	var rows []string
	for path, ops := range spec.Paths {
		// The SDK sends the spec's bare paths only (network.go, "One mount").
		if strings.HasPrefix(path, "/api/v1/") {
			continue
		}
		for _, m := range methods {
			opRaw, ok := ops[m]
			if !ok {
				continue
			}
			var op struct {
				Weight  *int   `json:"x-nexus-rate-limit-weight"`
				Formula string `json:"x-nexus-rate-limit-weight-formula"`
				Class   string `json:"x-nexus-rate-limit-class"`
			}
			if err := json.Unmarshal(opRaw, &op); err != nil {
				log.Fatalf("%s %s: %v", m, path, err)
			}
			method := strings.ToUpper(m)
			weight := 1
			if op.Weight != nil {
				weight = *op.Weight
			}
			if weight < 1 {
				log.Fatalf("%s %s: x-nexus-rate-limit-weight %d is below 1", method, path, weight)
			}
			perOrders := 0
			if op.Formula != "" {
				f := formula.FindStringSubmatch(op.Formula)
				if f == nil || f[1] != strconv.Itoa(weight) {
					log.Fatalf("%s %s: weight formula %q is not base + floor(order_count / n) with base %d; teach the transport it first",
						method, path, op.Formula, weight)
				}
				perOrders, _ = strconv.Atoi(f[2])
			}
			class := "classRequest"
			switch op.Class {
			case "":
			case "trading":
				// DELETE on the order surface is charged to the separate
				// cancel bucket; POST and PATCH to the order bucket.
				class = "classOrder"
				if method == "DELETE" {
					class = "classCancel"
				}
			default:
				log.Fatalf("%s %s: unknown x-nexus-rate-limit-class %q", method, path, op.Class)
			}
			rows = append(rows, fmt.Sprintf("{%q, %q, %s, %d, %d},", method, path, class, weight, perOrders))
		}
	}
	slices.Sort(rows)

	src := "// Code generated by genweights from the pinned spec; DO NOT EDIT.\n\n" +
		"package transport\n\n" +
		"// specCosts is every root-mount operation and what it costs, as the pinned\n" +
		"// spec marks it. Regenerate with go generate ./...\n" +
		"var specCosts = []opCost{\n" + strings.Join(rows, "\n") + "\n}\n"
	out, err := format.Source([]byte(src))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(os.Args[2], out, 0o644); err != nil {
		log.Fatal(err)
	}
}
