// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package models

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountFundingDirection.
const (
	AccountFundingDirectionPaid     AccountFundingDirection = "paid"
	AccountFundingDirectionReceived AccountFundingDirection = "received"
)

// Valid indicates whether the value is a known member of the AccountFundingDirection enum.
func (e AccountFundingDirection) Valid() bool {
	switch e {
	case AccountFundingDirectionPaid:
		return true
	case AccountFundingDirectionReceived:
		return true
	default:
		return false
	}
}

// Defines values for FillSide.
const (
	FillSideBuy  FillSide = "buy"
	FillSideSell FillSide = "sell"
)

// Valid indicates whether the value is a known member of the FillSide enum.
func (e FillSide) Valid() bool {
	switch e {
	case FillSideBuy:
		return true
	case FillSideSell:
		return true
	default:
		return false
	}
}

// Defines values for FillTakerOrMaker.
const (
	FillTakerOrMakerMaker FillTakerOrMaker = "maker"
	FillTakerOrMakerTaker FillTakerOrMaker = "taker"
)

// Valid indicates whether the value is a known member of the FillTakerOrMaker enum.
func (e FillTakerOrMaker) Valid() bool {
	switch e {
	case FillTakerOrMakerMaker:
		return true
	case FillTakerOrMakerTaker:
		return true
	default:
		return false
	}
}

// Defines values for MarketStatusStatus.
const (
	MarketStatusStatusActive MarketStatusStatus = "active"
	MarketStatusStatusHalted MarketStatusStatus = "halted"
)

// Valid indicates whether the value is a known member of the MarketStatusStatus enum.
func (e MarketStatusStatus) Valid() bool {
	switch e {
	case MarketStatusStatusActive:
		return true
	case MarketStatusStatusHalted:
		return true
	default:
		return false
	}
}

// Defines values for MarketSummaryStatus.
const (
	MarketSummaryStatusActive MarketSummaryStatus = "active"
	MarketSummaryStatusHalted MarketSummaryStatus = "halted"
)

// Valid indicates whether the value is a known member of the MarketSummaryStatus enum.
func (e MarketSummaryStatus) Valid() bool {
	switch e {
	case MarketSummaryStatusActive:
		return true
	case MarketSummaryStatusHalted:
		return true
	default:
		return false
	}
}

// Defines values for OrderSide.
const (
	OrderSideBuy  OrderSide = "Buy"
	OrderSideSell OrderSide = "Sell"
)

// Valid indicates whether the value is a known member of the OrderSide enum.
func (e OrderSide) Valid() bool {
	switch e {
	case OrderSideBuy:
		return true
	case OrderSideSell:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCancelled       OrderStatus = "Cancelled"
	OrderStatusExpired         OrderStatus = "Expired"
	OrderStatusFilled          OrderStatus = "Filled"
	OrderStatusOpen            OrderStatus = "Open"
	OrderStatusPartiallyFilled OrderStatus = "PartiallyFilled"
	OrderStatusRejected        OrderStatus = "Rejected"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCancelled:
		return true
	case OrderStatusExpired:
		return true
	case OrderStatusFilled:
		return true
	case OrderStatusOpen:
		return true
	case OrderStatusPartiallyFilled:
		return true
	case OrderStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for OrderHistoryEntrySide.
const (
	OrderHistoryEntrySideBuy  OrderHistoryEntrySide = "buy"
	OrderHistoryEntrySideSell OrderHistoryEntrySide = "sell"
)

// Valid indicates whether the value is a known member of the OrderHistoryEntrySide enum.
func (e OrderHistoryEntrySide) Valid() bool {
	switch e {
	case OrderHistoryEntrySideBuy:
		return true
	case OrderHistoryEntrySideSell:
		return true
	default:
		return false
	}
}

// Defines values for OrderHistoryEntryStatus.
const (
	OrderHistoryEntryStatusCancelled OrderHistoryEntryStatus = "Cancelled"
	OrderHistoryEntryStatusExpired   OrderHistoryEntryStatus = "Expired"
	OrderHistoryEntryStatusFilled    OrderHistoryEntryStatus = "Filled"
	OrderHistoryEntryStatusRejected  OrderHistoryEntryStatus = "Rejected"
)

// Valid indicates whether the value is a known member of the OrderHistoryEntryStatus enum.
func (e OrderHistoryEntryStatus) Valid() bool {
	switch e {
	case OrderHistoryEntryStatusCancelled:
		return true
	case OrderHistoryEntryStatusExpired:
		return true
	case OrderHistoryEntryStatusFilled:
		return true
	case OrderHistoryEntryStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for OrderRequestOrderType.
const (
	OrderRequestOrderTypeLimit            OrderRequestOrderType = "Limit"
	OrderRequestOrderTypeMarket           OrderRequestOrderType = "Market"
	OrderRequestOrderTypeStopLimit        OrderRequestOrderType = "StopLimit"
	OrderRequestOrderTypeStopMarket       OrderRequestOrderType = "StopMarket"
	OrderRequestOrderTypeTakeProfitLimit  OrderRequestOrderType = "TakeProfitLimit"
	OrderRequestOrderTypeTakeProfitMarket OrderRequestOrderType = "TakeProfitMarket"
	OrderRequestOrderTypeTrailingLimit    OrderRequestOrderType = "TrailingLimit"
	OrderRequestOrderTypeTrailingStop     OrderRequestOrderType = "TrailingStop"
)

// Valid indicates whether the value is a known member of the OrderRequestOrderType enum.
func (e OrderRequestOrderType) Valid() bool {
	switch e {
	case OrderRequestOrderTypeLimit:
		return true
	case OrderRequestOrderTypeMarket:
		return true
	case OrderRequestOrderTypeStopLimit:
		return true
	case OrderRequestOrderTypeStopMarket:
		return true
	case OrderRequestOrderTypeTakeProfitLimit:
		return true
	case OrderRequestOrderTypeTakeProfitMarket:
		return true
	case OrderRequestOrderTypeTrailingLimit:
		return true
	case OrderRequestOrderTypeTrailingStop:
		return true
	default:
		return false
	}
}

// Defines values for OrderRequestSide.
const (
	OrderRequestSideBuy  OrderRequestSide = "Buy"
	OrderRequestSideSell OrderRequestSide = "Sell"
)

// Valid indicates whether the value is a known member of the OrderRequestSide enum.
func (e OrderRequestSide) Valid() bool {
	switch e {
	case OrderRequestSideBuy:
		return true
	case OrderRequestSideSell:
		return true
	default:
		return false
	}
}

// Defines values for OrderRequestStp.
const (
	OrderRequestStpCancelNewest       OrderRequestStp = "CancelNewest"
	OrderRequestStpCancelOldest       OrderRequestStp = "CancelOldest"
	OrderRequestStpDecrementAndCancel OrderRequestStp = "DecrementAndCancel"
	OrderRequestStpLessThannil        OrderRequestStp = "<nil>"
)

// Valid indicates whether the value is a known member of the OrderRequestStp enum.
func (e OrderRequestStp) Valid() bool {
	switch e {
	case OrderRequestStpCancelNewest:
		return true
	case OrderRequestStpCancelOldest:
		return true
	case OrderRequestStpDecrementAndCancel:
		return true
	case OrderRequestStpLessThannil:
		return true
	default:
		return false
	}
}

// Defines values for OrderRequestTimeInForce.
const (
	OrderRequestTimeInForceFOK      OrderRequestTimeInForce = "FOK"
	OrderRequestTimeInForceGTC      OrderRequestTimeInForce = "GTC"
	OrderRequestTimeInForceIOC      OrderRequestTimeInForce = "IOC"
	OrderRequestTimeInForcePostOnly OrderRequestTimeInForce = "PostOnly"
)

// Valid indicates whether the value is a known member of the OrderRequestTimeInForce enum.
func (e OrderRequestTimeInForce) Valid() bool {
	switch e {
	case OrderRequestTimeInForceFOK:
		return true
	case OrderRequestTimeInForceGTC:
		return true
	case OrderRequestTimeInForceIOC:
		return true
	case OrderRequestTimeInForcePostOnly:
		return true
	default:
		return false
	}
}

// Defines values for OrderResultErrOutcome.
const (
	OrderResultErrOutcomeErr OrderResultErrOutcome = "err"
)

// Valid indicates whether the value is a known member of the OrderResultErrOutcome enum.
func (e OrderResultErrOutcome) Valid() bool {
	switch e {
	case OrderResultErrOutcomeErr:
		return true
	default:
		return false
	}
}

// Defines values for OrderResultOkOutcome.
const (
	OrderResultOkOutcomeOk OrderResultOkOutcome = "ok"
)

// Valid indicates whether the value is a known member of the OrderResultOkOutcome enum.
func (e OrderResultOkOutcome) Valid() bool {
	switch e {
	case OrderResultOkOutcomeOk:
		return true
	default:
		return false
	}
}

// Defines values for PositionSide.
const (
	PositionSideLong  PositionSide = "Long"
	PositionSideShort PositionSide = "Short"
)

// Valid indicates whether the value is a known member of the PositionSide enum.
func (e PositionSide) Valid() bool {
	switch e {
	case PositionSideLong:
		return true
	case PositionSideShort:
		return true
	default:
		return false
	}
}

// Defines values for ServiceHealthStatus.
const (
	ServiceHealthStatusDegraded ServiceHealthStatus = "degraded"
	ServiceHealthStatusDown     ServiceHealthStatus = "down"
	ServiceHealthStatusOk       ServiceHealthStatus = "ok"
	ServiceHealthStatusStarting ServiceHealthStatus = "starting"
)

// Valid indicates whether the value is a known member of the ServiceHealthStatus enum.
func (e ServiceHealthStatus) Valid() bool {
	switch e {
	case ServiceHealthStatusDegraded:
		return true
	case ServiceHealthStatusDown:
		return true
	case ServiceHealthStatusOk:
		return true
	case ServiceHealthStatusStarting:
		return true
	default:
		return false
	}
}

// Defines values for TradeSide.
const (
	TradeSideBuy  TradeSide = "buy"
	TradeSideSell TradeSide = "sell"
)

// Valid indicates whether the value is a known member of the TradeSide enum.
func (e TradeSide) Valid() bool {
	switch e {
	case TradeSideBuy:
		return true
	case TradeSideSell:
		return true
	default:
		return false
	}
}

// Defines values for FetchOHLCVParamsTimeframe.
const (
	FetchOHLCVParamsTimeframeN1h FetchOHLCVParamsTimeframe = "1h"
	FetchOHLCVParamsTimeframeN1m FetchOHLCVParamsTimeframe = "1m"
	FetchOHLCVParamsTimeframeN1s FetchOHLCVParamsTimeframe = "1s"
	FetchOHLCVParamsTimeframeN5m FetchOHLCVParamsTimeframe = "5m"
)

// Valid indicates whether the value is a known member of the FetchOHLCVParamsTimeframe enum.
func (e FetchOHLCVParamsTimeframe) Valid() bool {
	switch e {
	case FetchOHLCVParamsTimeframeN1h:
		return true
	case FetchOHLCVParamsTimeframeN1m:
		return true
	case FetchOHLCVParamsTimeframeN1s:
		return true
	case FetchOHLCVParamsTimeframeN5m:
		return true
	default:
		return false
	}
}

// AccountFunding A funding payment for the account.
type AccountFunding struct {
	// Amount Signed funding amount.
	Amount    *Decimal                 `json:"amount,omitempty"`
	Direction *AccountFundingDirection `json:"direction,omitempty"`

	// FundingRate Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	FundingRate *Decimal `json:"funding_rate,omitempty"`
	MarketId    *string  `json:"market_id,omitempty"`

	// PositionSize Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	PositionSize *Decimal `json:"position_size,omitempty"`

	// Timestamp Unix epoch timestamp in milliseconds.
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// AccountFundingDirection defines model for AccountFunding.Direction.
type AccountFundingDirection string

// AccountSummary defines model for AccountSummary.
type AccountSummary struct {
	// AvailableMargin Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	AvailableMargin *Decimal `json:"available_margin,omitempty"`

	// Balance Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Balance *Decimal `json:"balance,omitempty"`

	// Collateral Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Collateral *Decimal `json:"collateral,omitempty"`

	// Equity Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Equity    *Decimal    `json:"equity,omitempty"`
	Positions *[]Position `json:"positions,omitempty"`
}

// AdlClosureRecord One counterparty's forced closure within an ADL settlement.
type AdlClosureRecord struct {
	// AccountId 0x-prefixed address of the counterparty whose position was closed
	AccountId *string `json:"account_id,omitempty"`

	// PositionClosed Decimal quantity closed
	PositionClosed *Decimal `json:"position_closed,omitempty"`

	// SettlementAmount Decimal amount charged to the counterparty
	SettlementAmount *Decimal `json:"settlement_amount,omitempty"`
}

// AdlEventRecord Single ADL settlement (insurance fund depleted → counterparty closures). v0.21.
type AdlEventRecord struct {
	// BadDebtAbsorbedByFund Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	BadDebtAbsorbedByFund *Decimal `json:"bad_debt_absorbed_by_fund,omitempty"`

	// BankruptcyPrice Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	BankruptcyPrice      *Decimal            `json:"bankruptcy_price,omitempty"`
	CounterpartyClosures *[]AdlClosureRecord `json:"counterparty_closures,omitempty"`
	MarketId             *string             `json:"market_id,omitempty"`

	// Sequence Engine event sequence number
	Sequence *int `json:"sequence,omitempty"`

	// TargetAccount 0x-prefixed bankrupt account
	TargetAccount *string `json:"target_account,omitempty"`

	// Timestamp Unix ms
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// AgentInfo defines model for AgentInfo.
type AgentInfo struct {
	// Address Agent address (0x-prefixed)
	Address *string `json:"address,omitempty"`

	// ExpiresAt Expiry Unix ms
	ExpiresAt *TimestampMs `json:"expiresAt,omitempty"`

	// Label Optional label
	Label nullable.Nullable[string] `json:"label,omitempty"`

	// RegisteredAt Registration time Unix ms
	RegisteredAt *TimestampMs `json:"registeredAt,omitempty"`
}

// AgentRegistrationRequest defines model for AgentRegistrationRequest.
type AgentRegistrationRequest struct {
	// Agent Agent Ethereum address (0x-prefixed, 20 bytes) derived from the agent keypair
	Agent string `json:"agent"`

	// ExpiresAt Expiry as Unix ms. Optional — defaults to now+30d. Must be in [now+1d, now+90d].
	ExpiresAt *int64 `json:"expires_at,omitempty"`

	// Label Optional human-readable label for the agent (e.g. 'my-bot')
	Label *string `json:"label,omitempty"`

	// Nonce Monotonic nonce. Use the current Unix timestamp in ms as a safe starting value.
	Nonce int64 `json:"nonce"`

	// Signature EIP-712 signature over RegisterAgent{agent, expiresAt, nonce} from the wallet private key (0x-prefixed)
	Signature string `json:"signature"`

	// Wallet Owner wallet address (0x-prefixed, 20 bytes)
	Wallet string `json:"wallet"`
}

// AmendOrderRequest Atomic cancel-replace amend of a resting order. At least one of `price` (new limit price) or `size` (new quantity) must be present; an empty body is rejected with InvalidAmend.
type AmendOrderRequest struct {
	// Price Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Price *Decimal `json:"price,omitempty"`

	// Size Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Size *Decimal `json:"size,omitempty"`
}

// CancelOnDisconnectStatus Cancel-on-disconnect status for the authenticated account.
type CancelOnDisconnectStatus struct {
	// Active Whether COD will actually fire for this account: the account opt-in AND the exchange-side feature switch. When `enabled` is true but `active` is false, the exchange has the feature switched off and no cancel fires on disconnect.
	Active bool `json:"active"`

	// Enabled The account's own COD opt-in setting.
	Enabled bool `json:"enabled"`

	// GraceSecs Seconds the exchange waits after the last `/ws` disconnect before cancelling; a reconnect within the window disarms the cancel. Null when the feature is unavailable on this deployment.
	GraceSecs nullable.Nullable[int] `json:"grace_secs,omitempty"`
}

// Fill A single trade execution for the authenticated account
type Fill struct {
	// Fee Fee charged in USDX (decimal string)
	Fee *Decimal `json:"fee,omitempty"`

	// Id Fill ID
	Id            *string `json:"id,omitempty"`
	IsLiquidation *bool   `json:"is_liquidation,omitempty"`

	// MarketId Market (e.g. BTC-USDX-PERP)
	MarketId *string `json:"market_id,omitempty"`

	// OrderId Parent order ID
	OrderId *string `json:"order_id,omitempty"`

	// Price Executed price (decimal string)
	Price *Decimal  `json:"price,omitempty"`
	Side  *FillSide `json:"side,omitempty"`

	// Size Executed quantity (decimal string)
	Size         *Decimal          `json:"size,omitempty"`
	TakerOrMaker *FillTakerOrMaker `json:"taker_or_maker,omitempty"`

	// Timestamp Unix ms
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// FillSide defines model for Fill.Side.
type FillSide string

// FillTakerOrMaker defines model for Fill.TakerOrMaker.
type FillTakerOrMaker string

// FundingPremiumSample One premium-index observation between settlements, as served by `/markets/{market_id}/funding-samples`.
//
// Carries the premium and its timestamp, and nothing else. The settled funding rate, mark price and oracle price are properties of a settled *window*, not of an intra-window sample, and the event these samples are folded from does not carry them. Read `/markets/{market_id}/funding` for those — it returns `FundingSample`.
type FundingPremiumSample struct {
	// PremiumIndex `(trade_reference_price - oracle_price) / oracle_price` at the sample instant — the perpetual's own traded reference against the index, not the mark price.
	//
	// Reads `0` until the market has traded: with no trade reference available the value falls back to the oracle price, which makes the numerator exactly zero. A long run of `"0"` samples means the market has not traded, not that the perpetual is at parity with spot.
	PremiumIndex Decimal `json:"premium_index"`

	// Timestamp Unix epoch timestamp in milliseconds.
	Timestamp TimestampMs `json:"timestamp"`
}

// FundingSample A settled funding window, as served by `/markets/{market_id}/funding`: the realized rate for the window, plus the premium and prices of the last observation folded into it.
//
// This is not the shape of `/markets/{market_id}/funding-samples` — see `FundingPremiumSample`.
type FundingSample struct {
	// FundingRate Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	FundingRate *Decimal `json:"funding_rate,omitempty"`

	// MarkPrice Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	MarkPrice *Decimal `json:"mark_price,omitempty"`

	// OraclePrice Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	OraclePrice *Decimal `json:"oracle_price,omitempty"`

	// PremiumIndex Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	PremiumIndex *Decimal `json:"premium_index,omitempty"`

	// Timestamp Unix epoch timestamp in milliseconds.
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// JurisdictionError Error body returned with a `403` from a jurisdiction control. Flat `code`/`message`, matching the other top-level error bodies in this contract (`unauthorized`, `credits_frozen`) rather than the nested `BridgeError` envelope, which is scoped to `/v1/bridge`.
type JurisdictionError struct {
	// Code Stable machine-readable reason, identical to the `x-nexus-block-reason` response header. One of `RESTRICTED_JURISDICTION` (sanctions list — reads and writes alike), `US_RESTRICTED` (US write restriction — state-changing operations only) or `GEO_UNRESOLVED` (the request's origin could not be resolved and the write failed closed; not a statement about the caller's location). Match on this, not on `message`. All three are permanent for the caller's origin and must not be retried; treat an unrecognized code the same way.
	Code string `json:"code"`

	// Message Human-readable explanation. Wording is not stable and is not intended for programmatic matching.
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Message Must be exactly: "Sign in to Nexus Exchange"
	Message string `json:"message"`

	// Signature EIP-191 personal_sign hex (0x-prefixed, 65 bytes)
	Signature string `json:"signature"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Address Recovered Ethereum address (0x-prefixed)
	Address *string `json:"address,omitempty"`

	// Token Session token (64-char hex). Use as Bearer token for /keys endpoints.
	Token *string `json:"token,omitempty"`
}

// Market defines model for Market.
type Market struct {
	BaseAsset *string `json:"base_asset,omitempty"`

	// InitialMarginRate Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	InitialMarginRate *Decimal `json:"initial_margin_rate,omitempty"`

	// LotSize Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	LotSize *Decimal `json:"lot_size,omitempty"`

	// MaintenanceMarginRate Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	MaintenanceMarginRate *Decimal `json:"maintenance_margin_rate,omitempty"`
	MarketId              *string  `json:"market_id,omitempty"`
	MaxLeverage           *int     `json:"max_leverage,omitempty"`

	// MaxOrderSize Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	MaxOrderSize *Decimal `json:"max_order_size,omitempty"`

	// MinOrderSize Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	MinOrderSize *Decimal `json:"min_order_size,omitempty"`
	QuoteAsset   *string  `json:"quote_asset,omitempty"`

	// TickSize Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	TickSize *Decimal `json:"tick_size,omitempty"`
}

// MarketRiskParams Per-market risk parameters: margin rates and maximum leverage.
type MarketRiskParams struct {
	// InitialMarginRate Initial margin requirement as a decimal ratio (e.g., 0.05 = 5%)
	InitialMarginRate *Decimal `json:"initial_margin_rate,omitempty"`

	// MaintenanceMarginRate Maintenance margin requirement as a decimal ratio (e.g., 0.025 = 2.5%)
	MaintenanceMarginRate *Decimal `json:"maintenance_margin_rate,omitempty"`
	MarketId              *string  `json:"market_id,omitempty"`

	// MaxLeverage Maximum leverage allowed for this market
	MaxLeverage *int `json:"max_leverage,omitempty"`
}

// MarketStatus Per-market halt status (v0.21).
type MarketStatus struct {
	AdlEventCount *int                      `json:"adl_event_count,omitempty"`
	HaltReason    nullable.Nullable[string] `json:"halt_reason,omitempty"`
	HaltedAt      nullable.Nullable[int64]  `json:"halted_at,omitempty"`
	MarketId      *string                   `json:"market_id,omitempty"`
	Status        *MarketStatusStatus       `json:"status,omitempty"`
}

// MarketStatusStatus defines model for MarketStatus.Status.
type MarketStatusStatus string

// MarketSummary defines model for MarketSummary.
type MarketSummary struct {
	// AdlEventCount Cumulative ADL settlement events for this market
	AdlEventCount *int                      `json:"adl_event_count,omitempty"`
	HaltReason    nullable.Nullable[string] `json:"halt_reason,omitempty"`

	// HaltedAt Unix ms timestamp when market was halted
	HaltedAt nullable.Nullable[int64] `json:"halted_at,omitempty"`

	// LastTradePrice Last trade price ("what the market is trading at"). NOT the mark; the engine-derived mark is exposed separately.
	LastTradePrice nullable.Nullable[json.Number] `json:"last_trade_price,omitempty"`
	MarketId       *string                        `json:"market_id,omitempty"`

	// Status v0.21: halted when ADL pool exhausted
	Status     *MarketSummaryStatus `json:"status,omitempty"`
	TradeCount *int                 `json:"trade_count,omitempty"`
	Volume24h  *json.Number         `json:"volume_24h,omitempty"`
}

// MarketSummaryStatus v0.21: halted when ADL pool exhausted
type MarketSummaryStatus string

// Order defines model for Order.
type Order struct {
	AccountId *string `json:"account_id,omitempty"`

	// CancellationReason Why the order reached a terminal `Cancelled` or `Rejected` status. `null` for every other status, and for a terminal order the engine recorded no cause for. The key is always present.
	//
	// **Two wire shapes.** The engine's reason type is an externally tagged enum, so every cause except self-trade prevention is a bare string, while self-trade prevention is a single-key object naming the mode that fired: `{"Stp": "CancelNewest"}`. Branch on the JSON type before reading the value.
	//
	// The string form is one of `User` (an explicit cancel or cancel-all), `SlippageCap` (a market order's running fill VWAP left the `max_slippage_bps` band — see that field), `Liquidation` (cancelled ahead of a liquidation, or the unfilled remainder of one), `Expired` (an IOC, FOK or market remainder that cannot rest on the book), `MarketHalt`, `AmendReplace` (carried on the *original* order of an atomic cancel-replace via `PATCH /orders/{order_id}`), `InsufficientLiquidity` (a stop, stop-limit or trailing stop fired into an empty opposite side), `BracketClosed` or `BracketFlipped` (a bracket child whose parent position closed to zero or flipped sign), or `PriceBandExceeded` (the order-vs-mark price-band collar rejected it). The object form's only key today is `Stp`, whose value is `CancelNewest`, `CancelOldest` or `DecrementAndCancel`.
	//
	// **Treat the value as open.** Causes are added as the engine gains them, and this is not a closed enum: match the ones you handle and surface anything else verbatim rather than failing to parse. A client pinned to an older spec tag will meet causes it does not know.
	//
	// `GET /orders/history` reports the same causes in a **different encoding** — `OrderHistoryEntry.cancellation_reason` is always a string and renders the self-trade case as `Stp(CancelNewest)`, not as an object. Do not compare values across the two surfaces.
	CancellationReason nullable.Nullable[Order_CancellationReason] `json:"cancellation_reason,omitempty"`

	// CreatedAt Unix epoch timestamp in milliseconds.
	CreatedAt *TimestampMs `json:"created_at,omitempty"`

	// FilledQty Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	FilledQty *Decimal `json:"filled_qty,omitempty"`
	Id        *string  `json:"id,omitempty"`

	// LimitOffsetBps Fire-time limit offset in basis points, echoed for `TrailingLimit` orders (see the `OrderRequest.limit_offset_bps` placement field); null for other order types.
	LimitOffsetBps nullable.Nullable[int] `json:"limit_offset_bps,omitempty"`
	MarketId       *string                `json:"market_id,omitempty"`

	// MaxSlippageBps Slippage cap in basis points, echoed for orders placed with one (see the `OrderRequest.max_slippage_bps` placement field); null for orders placed without a cap.
	MaxSlippageBps nullable.Nullable[int] `json:"max_slippage_bps,omitempty"`
	OrderType      *string                `json:"order_type,omitempty"`

	// Price Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Price *Decimal `json:"price,omitempty"`

	// Quantity Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Quantity *Decimal     `json:"quantity,omitempty"`
	Side     *OrderSide   `json:"side,omitempty"`
	Status   *OrderStatus `json:"status,omitempty"`

	// Stp The self-trade prevention mode the order was placed with, echoed back (see the `OrderRequest.stp` placement field for what each mode does). `null` for an order placed without one, which is the default and means self-matching was allowed. One of `CancelNewest`, `CancelOldest` or `DecrementAndCancel`.
	//
	// Deliberately not a closed enum here, for the same reason as `cancellation_reason`: the mode set has changed before (D-026 supersedes D-014) and a mode added later must not break a client pinned to an older spec tag. `OrderRequest.stp` does enumerate the modes, because there the value is one you supply and the server validates it.
	Stp         nullable.Nullable[string] `json:"stp,omitempty"`
	TimeInForce *string                   `json:"time_in_force,omitempty"`

	// UpdatedAt Unix epoch timestamp in milliseconds.
	UpdatedAt *TimestampMs `json:"updated_at,omitempty"`
}

// OrderCancellationReason1 Any cause other than self-trade prevention, as a bare string.
type OrderCancellationReason1 = string

// OrderCancellationReason2 A cause that carries a payload. Exactly one key, naming the cause. `additionalProperties` is deliberately not closed, so a cause added later does not invalidate this schema.
type OrderCancellationReason2 struct {
	// Stp Self-trade prevention cancelled the order; the value is the STP mode that fired (`CancelNewest`, `CancelOldest` or `DecrementAndCancel`).
	Stp *string `json:"Stp,omitempty"`
}

// Order_CancellationReason Why the order reached a terminal `Cancelled` or `Rejected` status. `null` for every other status, and for a terminal order the engine recorded no cause for. The key is always present.
//
// **Two wire shapes.** The engine's reason type is an externally tagged enum, so every cause except self-trade prevention is a bare string, while self-trade prevention is a single-key object naming the mode that fired: `{"Stp": "CancelNewest"}`. Branch on the JSON type before reading the value.
//
// The string form is one of `User` (an explicit cancel or cancel-all), `SlippageCap` (a market order's running fill VWAP left the `max_slippage_bps` band — see that field), `Liquidation` (cancelled ahead of a liquidation, or the unfilled remainder of one), `Expired` (an IOC, FOK or market remainder that cannot rest on the book), `MarketHalt`, `AmendReplace` (carried on the *original* order of an atomic cancel-replace via `PATCH /orders/{order_id}`), `InsufficientLiquidity` (a stop, stop-limit or trailing stop fired into an empty opposite side), `BracketClosed` or `BracketFlipped` (a bracket child whose parent position closed to zero or flipped sign), or `PriceBandExceeded` (the order-vs-mark price-band collar rejected it). The object form's only key today is `Stp`, whose value is `CancelNewest`, `CancelOldest` or `DecrementAndCancel`.
//
// **Treat the value as open.** Causes are added as the engine gains them, and this is not a closed enum: match the ones you handle and surface anything else verbatim rather than failing to parse. A client pinned to an older spec tag will meet causes it does not know.
//
// `GET /orders/history` reports the same causes in a **different encoding** — `OrderHistoryEntry.cancellation_reason` is always a string and renders the self-trade case as `Stp(CancelNewest)`, not as an object. Do not compare values across the two surfaces.
type Order_CancellationReason struct {
	union json.RawMessage
}

// OrderSide defines model for Order.Side.
type OrderSide string

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderBook CCXT-compatible order book. Bids/asks are [price, amount] arrays.
type OrderBook struct {
	Asks     *[][]interface{} `json:"asks,omitempty"`
	Bids     *[][]interface{} `json:"bids,omitempty"`
	Datetime *string          `json:"datetime,omitempty"`
	Nonce    *int64           `json:"nonce,omitempty"`
	Symbol   *string          `json:"symbol,omitempty"`

	// Timestamp Unix epoch timestamp in milliseconds.
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// OrderHistoryEntry A terminal-status order (filled / cancelled / rejected / expired).
type OrderHistoryEntry struct {
	// CancellationReason Why the order was cancelled or rejected; `null` for any other status. Always a **string** on this route, including for self-trade prevention, which renders as `Stp(CancelNewest)` — this surface stringifies the engine's reason type, so the encoding differs from `Order.cancellation_reason`, where that same cause is the object `{"Stp": "CancelNewest"}`. The cause set is otherwise identical, and equally open — see `Order.cancellation_reason` for the full list.
	CancellationReason nullable.Nullable[string] `json:"cancellation_reason,omitempty"`

	// CompletedAtMs Unix epoch timestamp in milliseconds.
	CompletedAtMs *TimestampMs `json:"completed_at_ms,omitempty"`

	// CreatedAtMs Unix epoch timestamp in milliseconds.
	CreatedAtMs *TimestampMs `json:"created_at_ms,omitempty"`

	// FilledQty Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	FilledQty *Decimal `json:"filled_qty,omitempty"`
	Id        *string  `json:"id,omitempty"`
	MarketId  *string  `json:"market_id,omitempty"`

	// OrderType limit | market | stop_* | take_profit_* | trailing_stop | trailing_limit
	OrderType *string `json:"order_type,omitempty"`

	// Price Limit price; null for market orders.
	Price nullable.Nullable[Decimal] `json:"price,omitempty"`
	Side  *OrderHistoryEntrySide     `json:"side,omitempty"`

	// Size Original quantity.
	Size   *Decimal                 `json:"size,omitempty"`
	Status *OrderHistoryEntryStatus `json:"status,omitempty"`
}

// OrderHistoryEntrySide defines model for OrderHistoryEntry.Side.
type OrderHistoryEntrySide string

// OrderHistoryEntryStatus defines model for OrderHistoryEntry.Status.
type OrderHistoryEntryStatus string

// OrderRequest Order placement request. Supports plain `Limit` / `Market` orders and six conditional order types (`StopLimit`, `StopMarket`, `TakeProfitLimit`, `TakeProfitMarket`, `TrailingStop`, `TrailingLimit`). Field requirements depend on `order_type`:
//
// - **Limit-family** (`Limit`, `StopLimit`, `TakeProfitLimit`) require a limit `price`.
// - **Triggerable, non-trailing** orders (`StopLimit`, `StopMarket`, `TakeProfitLimit`, `TakeProfitMarket`) require a `trigger_price` (the legacy `stop_price` field is accepted as a fallback when `trigger_price` is absent).
// - **`TrailingStop`** is market-only — it fires as a market order — and requires `trailing_offset_bps`. It does not take a limit `price` or a `trigger_price` (the trigger anchor is derived from the mark price and the offset).
// - **`TrailingLimit`** trails like `TrailingStop` but fires a limit order instead of a market order. It requires both `trailing_offset_bps` (the trailing trigger) and `limit_offset_bps` (the fire-time limit offset). It does not take `price`, `trigger_price`, or `stop_price`; the limit price is computed at fire time from the mark that crossed the offset.
type OrderRequest struct {
	// LimitOffsetBps Offset in basis points for the fired limit price (`TrailingLimit` only; required together with `trailing_offset_bps`). When the trailing trigger fires at `fire_price`, the injected limit order rests at `fire_price` * (1 + offset) for buys / * (1 - offset) for sells, tick-rounded toward the tighter bound. A value of 0 rests the limit exactly at `fire_price`. Ignored for other order types.
	LimitOffsetBps nullable.Nullable[int] `json:"limit_offset_bps,omitempty"`
	MarketId       string                 `json:"market_id"`

	// MaxSlippageBps Server-enforced slippage cap in basis points (1 bp = 0.01%). Omit the field for no cap. When set, the engine captures the book mid-price `(best_bid + best_ask) / 2` once at submission and requires the order's running fill VWAP to stay inside `mid ± mid × bps / 10000` as it walks the book. Fills made before the cap binds stand; the fill that would push the VWAP outside the band is not made and the unfilled remainder is cancelled — the order comes back on the normal `201` with `status` `Cancelled` and `cancellation_reason` `SlippageCap`, not as an error. Because the reference is the mid captured server-side at submission and the bound is on the running VWAP rather than on the worst individual fill, this is a stricter guarantee than a marketable limit price derived client-side from a previously sampled reference price.
	//
	// Applies to the market family: `Market`, plus `StopMarket`, `TakeProfitMarket`, and `TrailingStop`, which carry the field through their conversion and have the cap applied when they fire as market orders. Accepted but ignored on `Limit`, `StopLimit`, `TakeProfitLimit`, and `TrailingLimit` — a limit order already fills at its limit price or better.
	//
	// Two edges worth knowing. A mid-price requires **both** sides of the book to be non-empty, so a capped order submitted while either side is empty is rejected with `InsufficientLiquidity` (a `400` on `POST /orders`, an `err` item on `POST /orders/batch`) — including when the empty side is the order's own and the order could otherwise have filled. And `0` does not mean "no cap": it collapses the band onto the mid exactly, so against any book with a non-zero spread the order cancels with zero fills. `POST /orders/preview` accepts the field but does not apply it — `expected_fill_vwap` always walks the full book.
	MaxSlippageBps nullable.Nullable[int] `json:"max_slippage_bps,omitempty"`

	// OrderType Order type. `Limit` and `Market` are unconditional. The remaining six are conditional: `StopLimit` / `StopMarket` fire when the mark price crosses `trigger_price` in the adverse direction; `TakeProfitLimit` / `TakeProfitMarket` fire on the favorable direction; `TrailingStop` fires as a market order when the mark retraces from its best-seen extreme by `trailing_offset_bps`; `TrailingLimit` fires the same way but rests a limit order priced off the fire price by `limit_offset_bps`. See the schema description for per-type field requirements.
	OrderType OrderRequestOrderType `json:"order_type"`

	// Price Limit price. Required for limit-family orders (`Limit`, `StopLimit`, `TakeProfitLimit`); omit for market-family and trailing orders.
	Price *Decimal `json:"price,omitempty"`

	// Quantity Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Quantity   Decimal          `json:"quantity"`
	ReduceOnly *bool            `json:"reduce_only,omitempty"`
	Side       OrderRequestSide `json:"side"`

	// StopPrice **Deprecated** — use `trigger_price` instead. Legacy trigger threshold for the stop / take-profit family. Accepted as a fallback only when `trigger_price` is absent; when both are supplied, `trigger_price` wins. Ignored for `Limit`, `Market`, `TrailingStop`, and `TrailingLimit` orders.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	StopPrice nullable.Nullable[Decimal] `json:"stop_price,omitempty"`

	// Stp Opt-in self-trade prevention. Omit the field, or send `null`, to allow self-matching — that is the default and the industry-standard behaviour, and the engine will fill your order against your own resting order. Set a mode to have the engine intervene when a taker meets a maker on the same account instead.
	//
	// `CancelNewest` cancels the incoming taker and leaves the maker resting; the taker stops walking the book entirely, so remaining taker size beyond that maker is cancelled too. `CancelOldest` cancels the resting maker and lets the taker carry on against other accounts' makers. `DecrementAndCancel` reduces both sides by `min(taker_remaining, maker_size)` and cancels the smaller side, leaving the larger to continue at the reduced quantity.
	//
	// The check is applied **per encountered same-account maker**, not once at order entry, so a taker crossing several of your own makers is evaluated at each one. It sits in the shared matching path, so it applies to every order type rather than a subset. When a mode cancels an order, that order comes back with `cancellation_reason` set to the object `{"Stp": "<mode>"}` — see `Order.cancellation_reason`.
	Stp nullable.Nullable[OrderRequestStp] `json:"stp,omitempty"`

	// TimeInForce Time-in-force policy. `PostOnly` rejects the order if it would take liquidity (cross the book) on entry, guaranteeing it rests as a maker.
	TimeInForce OrderRequestTimeInForce `json:"time_in_force"`

	// TrailingOffsetBps Trailing offset in basis points (1 bp = 0.01%). Required for `TrailingStop` and `TrailingLimit` orders; ignored for all other order types. The trailing trigger fires once the mark price retraces from its best-seen extreme by this many basis points: `TrailingStop` fires a market order, `TrailingLimit` fires a limit order priced by `limit_offset_bps`. A value of `0` is accepted and fires the trigger at the first mark-price evaluation after placement (no retracement required).
	TrailingOffsetBps nullable.Nullable[int] `json:"trailing_offset_bps,omitempty"`

	// TriggerPrice Canonical trigger threshold for triggerable, non-trailing orders (`StopLimit`, `StopMarket`, `TakeProfitLimit`, `TakeProfitMarket`), which require it (the legacy `stop_price` field is accepted as a fallback when this is omitted). Not used by `Limit`, `Market`, `TrailingStop`, or `TrailingLimit` orders.
	TriggerPrice nullable.Nullable[Decimal] `json:"trigger_price,omitempty"`
}

// OrderRequestOrderType Order type. `Limit` and `Market` are unconditional. The remaining six are conditional: `StopLimit` / `StopMarket` fire when the mark price crosses `trigger_price` in the adverse direction; `TakeProfitLimit` / `TakeProfitMarket` fire on the favorable direction; `TrailingStop` fires as a market order when the mark retraces from its best-seen extreme by `trailing_offset_bps`; `TrailingLimit` fires the same way but rests a limit order priced off the fire price by `limit_offset_bps`. See the schema description for per-type field requirements.
type OrderRequestOrderType string

// OrderRequestSide defines model for OrderRequest.Side.
type OrderRequestSide string

// OrderRequestStp Opt-in self-trade prevention. Omit the field, or send `null`, to allow self-matching — that is the default and the industry-standard behaviour, and the engine will fill your order against your own resting order. Set a mode to have the engine intervene when a taker meets a maker on the same account instead.
//
// `CancelNewest` cancels the incoming taker and leaves the maker resting; the taker stops walking the book entirely, so remaining taker size beyond that maker is cancelled too. `CancelOldest` cancels the resting maker and lets the taker carry on against other accounts' makers. `DecrementAndCancel` reduces both sides by `min(taker_remaining, maker_size)` and cancels the smaller side, leaving the larger to continue at the reduced quantity.
//
// The check is applied **per encountered same-account maker**, not once at order entry, so a taker crossing several of your own makers is evaluated at each one. It sits in the shared matching path, so it applies to every order type rather than a subset. When a mode cancels an order, that order comes back with `cancellation_reason` set to the object `{"Stp": "<mode>"}` — see `Order.cancellation_reason`.
type OrderRequestStp string

// OrderRequestTimeInForce Time-in-force policy. `PostOnly` rejects the order if it would take liquidity (cross the book) on entry, guaranteeing it rests as a maker.
type OrderRequestTimeInForce string

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	Fills *[]Fill `json:"fills,omitempty"`
	Order *Order  `json:"order,omitempty"`
}

// OrderResult One entry in the array returned by POST /orders/batch. The batch is sequential and non-atomic, so each entry independently reports either a placed order or a per-order rejection, in request order. Internally tagged by `outcome`: `ok` carries the same `{ order, fills }` shape as POST /orders, `err` carries the same `{ error, message }` shape as the global error envelope.
type OrderResult struct {
	union json.RawMessage
}

// OrderResultErr A rejected order in a batch result (outcome `err`). Mirrors the global error envelope.
type OrderResultErr struct {
	// Error Machine-readable error code.
	Error string `json:"error"`

	// Message Human-readable error message.
	Message string                `json:"message"`
	Outcome OrderResultErrOutcome `json:"outcome"`
}

// OrderResultErrOutcome defines model for OrderResultErr.Outcome.
type OrderResultErrOutcome string

// OrderResultOk A placed order in a batch result (outcome `ok`).
type OrderResultOk struct {
	Fills   *[]Fill              `json:"fills,omitempty"`
	Order   Order                `json:"order"`
	Outcome OrderResultOkOutcome `json:"outcome"`
}

// OrderResultOkOutcome defines model for OrderResultOk.Outcome.
type OrderResultOkOutcome string

// Position An open position with per-position risk detail. Enriched risk fields are derived strictly from indexer-mirrored state (no engine round-trip, to stay on the low-latency read path): when an input is not mirrored, the field is `null` and its companion `<field>_error` carries a machine-readable reason rather than a fabricated number. Monetary fields are lossless decimal strings; leverage fields are JSON numbers.
type Position struct {
	// EntryPrice Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	EntryPrice *Decimal `json:"entry_price,omitempty"`

	// FundingPaid Cumulative funding paid on this position, as a decimal string. Sign is **paid-positive**: a positive value means the position has paid funding, a negative value means it has received funding. Always present: `"0"` when no funding has accrued. Bounded by the funding history the indexer retains.
	FundingPaid *Decimal `json:"funding_paid,omitempty"`

	// Leverage Position leverage (the account's leverage multiplier for this position). Currently always `null`: deriving it needs the user's leverage setting or account equity/allocated margin, which the indexer does not mirror; when `null`, `leverage_error` carries the reason. Do not infer leverage from `margin_used` — that collapses to `1/initial_margin_rate`, a per-market constant, not the real leverage.
	Leverage nullable.Nullable[json.Number] `json:"leverage,omitempty"`

	// LeverageError Machine-readable reason `leverage` is `null`, or `null` when `leverage` is populated. Currently always `margin_state_not_mirrored`.
	LeverageError nullable.Nullable[string] `json:"leverage_error,omitempty"`

	// LiquidationPrice Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	LiquidationPrice *Decimal `json:"liquidation_price,omitempty"`

	// MarginUsed Initial-margin requirement held against this position (`notional_value × initial_margin_rate`, under the engine's cross-margin model), as a decimal string. Isolated/custom margin allocations are not mirrored by the indexer. `null` when a required input is unavailable — see `margin_used_error`.
	MarginUsed nullable.Nullable[Decimal] `json:"margin_used,omitempty"`

	// MarginUsedError Machine-readable reason `margin_used` is `null` (e.g. `mark_price_unavailable`, `margin_rate_unavailable`), or `null` when populated.
	MarginUsedError nullable.Nullable[string] `json:"margin_used_error,omitempty"`
	MarketId        *string                   `json:"market_id,omitempty"`

	// MaxLeverage Maximum leverage allowed for this market (from market risk params), as an integer matching `max_leverage` on `/markets/{market_id}/risk-params`. `null` when market params are unavailable — see `max_leverage_error`.
	MaxLeverage nullable.Nullable[int] `json:"max_leverage,omitempty"`

	// MaxLeverageError Machine-readable reason `max_leverage` is `null` (e.g. `market_params_unavailable`), or `null` when populated.
	MaxLeverageError nullable.Nullable[string] `json:"max_leverage_error,omitempty"`

	// NotionalValue Position notional value (|size| × mark price), as a decimal string. `null` when the mark price is unavailable — see `notional_value_error`.
	NotionalValue nullable.Nullable[Decimal] `json:"notional_value,omitempty"`

	// NotionalValueError Machine-readable reason `notional_value` is `null` (e.g. `mark_price_unavailable`), or `null` when populated.
	NotionalValueError nullable.Nullable[string] `json:"notional_value_error,omitempty"`

	// RealizedPnl Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	RealizedPnl *Decimal `json:"realized_pnl,omitempty"`

	// Roe Return on equity: `unrealized_pnl / margin_used` (return on initial margin), as a decimal string. `null` when a required input is unavailable or margin is zero — see `roe_error`.
	Roe nullable.Nullable[Decimal] `json:"roe,omitempty"`

	// RoeError Machine-readable reason `roe` is `null` (e.g. `mark_price_unavailable`, `margin_rate_unavailable`, `margin_used_zero`), or `null` when populated.
	RoeError nullable.Nullable[string] `json:"roe_error,omitempty"`
	Side     *PositionSide             `json:"side,omitempty"`

	// Size Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	Size *Decimal `json:"size,omitempty"`

	// UnrealizedPnl Arbitrary-precision decimal serialized as a string (lossless). Parse with a decimal type, never a float.
	UnrealizedPnl *Decimal `json:"unrealized_pnl,omitempty"`
}

// PositionSide defines model for Position.Side.
type PositionSide string

// ServiceHealth Aggregate health for the indexer/engine/oracle/bots, consumed by status.nexus.xyz. The `services` object carries per-component detail; only the common fields are documented here.
type ServiceHealth struct {
	// Services Per-component status (indexer, engine, oracle, bots). Component detail is informational and may evolve; clients should rely on the top-level `status`.
	Services *map[string]interface{} `json:"services,omitempty"`

	// Status Worst-of across all components.
	Status *ServiceHealthStatus `json:"status,omitempty"`

	// TimestampMs Unix epoch timestamp in milliseconds.
	TimestampMs *TimestampMs `json:"timestamp_ms,omitempty"`
}

// ServiceHealthStatus Worst-of across all components.
type ServiceHealthStatus string

// SetCancelOnDisconnectRequest Cancel-on-disconnect opt-in change for the authenticated account.
type SetCancelOnDisconnectRequest struct {
	// Enabled True to enable COD for the account, false to disable.
	Enabled bool `json:"enabled"`
}

// StatsSnapshot Aggregate venue statistics. `/stats` augments the snapshot with rolling unique-trader counts.
type StatsSnapshot struct {
	Connected      *bool        `json:"connected,omitempty"`
	EventsPerSec   *json.Number `json:"events_per_sec,omitempty"`
	EventsReceived *int64       `json:"events_received,omitempty"`
	FillsTotal     *int64       `json:"fills_total,omitempty"`
	GapCount       *int64       `json:"gap_count,omitempty"`

	// Health Health classification (e.g. Healthy / Degraded / Unhealthy).
	Health              *string                        `json:"health,omitempty"`
	HighestSequenceSeen *int64                         `json:"highest_sequence_seen,omitempty"`
	LastEventMs         nullable.Nullable[TimestampMs] `json:"last_event_ms,omitempty"`
	LiquidationsTotal   *int64                         `json:"liquidations_total,omitempty"`

	// UniqueTraders24h Rolling 24h unique traders (DAU). Present on `/stats`.
	UniqueTraders24h *int64 `json:"unique_traders_24h,omitempty"`

	// UniqueTraders30d Rolling 30d unique traders (MAU). Present on `/stats`.
	UniqueTraders30d *int64 `json:"unique_traders_30d,omitempty"`

	// UniqueTraders7d Rolling 7d unique traders (WAU). Present on `/stats`.
	UniqueTraders7d *int64 `json:"unique_traders_7d,omitempty"`
	UptimeSeconds   *int64 `json:"uptime_seconds,omitempty"`
}

// ThroughputSample One point in the venue throughput ring buffer (1s cadence, capped at 3600 points).
type ThroughputSample struct {
	Fills *int64 `json:"fills,omitempty"`

	// Timestamp Unix seconds.
	Timestamp *int64 `json:"timestamp,omitempty"`
}

// Ticker CCXT-compatible ticker with 24h statistics
type Ticker struct {
	Ask        nullable.Nullable[json.Number] `json:"ask,omitempty"`
	AskVolume  nullable.Nullable[json.Number] `json:"askVolume,omitempty"`
	BaseVolume nullable.Nullable[json.Number] `json:"baseVolume,omitempty"`
	Bid        nullable.Nullable[json.Number] `json:"bid,omitempty"`
	BidVolume  nullable.Nullable[json.Number] `json:"bidVolume,omitempty"`
	Change     nullable.Nullable[json.Number] `json:"change,omitempty"`
	Close      nullable.Nullable[json.Number] `json:"close,omitempty"`
	Datetime   *string                        `json:"datetime,omitempty"`
	High       nullable.Nullable[json.Number] `json:"high,omitempty"`
	IndexPrice nullable.Nullable[json.Number] `json:"indexPrice,omitempty"`
	Info       *map[string]interface{}        `json:"info,omitempty"`
	Last       nullable.Nullable[json.Number] `json:"last,omitempty"`
	Low        nullable.Nullable[json.Number] `json:"low,omitempty"`

	// MarkPrice Engine-derived mark price (oracle + premium-index), falling back to the last trade until the first mark-price poll lands. The raw last trade is carried by `last`.
	MarkPrice   nullable.Nullable[json.Number] `json:"markPrice,omitempty"`
	Open        nullable.Nullable[json.Number] `json:"open,omitempty"`
	Percentage  nullable.Nullable[json.Number] `json:"percentage,omitempty"`
	QuoteVolume nullable.Nullable[json.Number] `json:"quoteVolume,omitempty"`
	Symbol      *string                        `json:"symbol,omitempty"`

	// Timestamp Unix ms
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// TimestampMs Unix epoch timestamp in milliseconds.
type TimestampMs = int64

// Trade CCXT-compatible trade record
type Trade struct {
	Amount        *json.Number              `json:"amount,omitempty"`
	Cost          *json.Number              `json:"cost,omitempty"`
	Datetime      *string                   `json:"datetime,omitempty"`
	Id            *string                   `json:"id,omitempty"`
	Info          *map[string]interface{}   `json:"info,omitempty"`
	IsLiquidation *bool                     `json:"is_liquidation,omitempty"`
	Price         *json.Number              `json:"price,omitempty"`
	Side          *TradeSide                `json:"side,omitempty"`
	Symbol        *string                   `json:"symbol,omitempty"`
	TakerOrMaker  nullable.Nullable[string] `json:"takerOrMaker,omitempty"`

	// Timestamp Unix epoch timestamp in milliseconds.
	Timestamp *TimestampMs `json:"timestamp,omitempty"`
}

// TradeSide defines model for Trade.Side.
type TradeSide string

// Cursor defines model for Cursor.
type Cursor = string

// MarketId defines model for MarketId.
type MarketId = string

// RateLimited defines model for RateLimited.
type RateLimited interface{}

// RestrictedJurisdiction Error body returned with a `403` from a jurisdiction control. Flat `code`/`message`, matching the other top-level error bodies in this contract (`unauthorized`, `credits_frozen`) rather than the nested `BridgeError` envelope, which is scoped to `/v1/bridge`.
type RestrictedJurisdiction = JurisdictionError

// Unauthorized defines model for Unauthorized.
type Unauthorized interface{}

// FetchFillsParams defines parameters for FetchFills.
type FetchFillsParams struct {
	// Limit Maximum fills to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor returned in the previous response's `X-Next-Cursor` header. Omit to fetch the first page. Treat the token as opaque: its format is not part of the contract and may change. Cursors do not expire. A malformed (unparseable) cursor is not an error — the server serves the first page. A well-formed cursor whose exact position has since been evicted from the retained window is not reset to the first page: pagination resumes at the nearest surviving boundary, so a resumed response is a continuation, not a fresh first page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// FetchAccountFundingParams defines parameters for FetchAccountFunding.
type FetchAccountFundingParams struct {
	// Limit Maximum records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// FetchAdlEventsParams defines parameters for FetchAdlEvents.
type FetchAdlEventsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// FetchOHLCVParams defines parameters for FetchOHLCV.
type FetchOHLCVParams struct {
	Timeframe *FetchOHLCVParamsTimeframe `form:"timeframe,omitempty" json:"timeframe,omitempty"`
	Limit     *int                       `form:"limit,omitempty" json:"limit,omitempty"`
}

// FetchOHLCVParamsTimeframe defines parameters for FetchOHLCV.
type FetchOHLCVParamsTimeframe string

// FetchFundingParams defines parameters for FetchFunding.
type FetchFundingParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// FetchFundingSamplesParams defines parameters for FetchFundingSamples.
type FetchFundingSamplesParams struct {
	// Limit Maximum samples to return (capped at 480).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// FetchTradesParams defines parameters for FetchTrades.
type FetchTradesParams struct {
	// Limit Number of trades to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor returned in the previous response's `X-Next-Cursor` header. Omit to fetch the first page. Treat the token as opaque: its format is not part of the contract and may change. Cursors do not expire. A malformed (unparseable) cursor is not an error — the server serves the first page. A well-formed cursor whose exact position has since been evicted from the retained window is not reset to the first page: pagination resumes at the nearest surviving boundary, so a resumed response is a continuation, not a fresh first page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CancelAllOrdersParams defines parameters for CancelAllOrders.
type CancelAllOrdersParams struct {
	// MarketId Cancel only orders on this market
	MarketId *string `form:"market_id,omitempty" json:"market_id,omitempty"`
}

// CreateOrdersBatchJSONBody defines parameters for CreateOrdersBatch.
type CreateOrdersBatchJSONBody = []OrderRequest

// FetchOrderHistoryParams defines parameters for FetchOrderHistory.
type FetchOrderHistoryParams struct {
	// Limit Maximum records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor returned in the previous response's `X-Next-Cursor` header. Omit to fetch the first page. Treat the token as opaque: its format is not part of the contract and may change. Cursors do not expire. A malformed (unparseable) cursor is not an error — the server serves the first page. A well-formed cursor whose exact position has since been evicted from the retained window is not reset to the first page: pagination resumes at the nearest surviving boundary, so a resumed response is a continuation, not a fresh first page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CancelOrderParams defines parameters for CancelOrder.
type CancelOrderParams struct {
	// MarketId Market the order rests on (required for routing).
	MarketId string `form:"market_id" json:"market_id"`
}

// FetchOrderParams defines parameters for FetchOrder.
type FetchOrderParams struct {
	// MarketId Market the order rests on (required for routing).
	MarketId string `form:"market_id" json:"market_id"`
}

// EditOrderParams defines parameters for EditOrder.
type EditOrderParams struct {
	// MarketId Market the order rests on (required for routing).
	MarketId string `form:"market_id" json:"market_id"`
}

// ConnectStreamParams defines parameters for ConnectStream.
type ConnectStreamParams struct {
	// Token Short-lived token from POST /ws-tokens
	Token string `form:"token" json:"token"`
}

// ConnectWebSocketParams defines parameters for ConnectWebSocket.
type ConnectWebSocketParams struct {
	// Token Short-lived token from POST /ws/token
	Token string `form:"token" json:"token"`
}

// SetCancelOnDisconnectJSONRequestBody defines body for SetCancelOnDisconnect for application/json ContentType.
type SetCancelOnDisconnectJSONRequestBody = SetCancelOnDisconnectRequest

// RegisterAgentJSONRequestBody defines body for RegisterAgent for application/json ContentType.
type RegisterAgentJSONRequestBody = AgentRegistrationRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderRequest

// CreateOrdersBatchJSONRequestBody defines body for CreateOrdersBatch for application/json ContentType.
type CreateOrdersBatchJSONRequestBody = CreateOrdersBatchJSONBody

// EditOrderJSONRequestBody defines body for EditOrder for application/json ContentType.
type EditOrderJSONRequestBody = AmendOrderRequest

// AsOrderCancellationReason1 returns the union data inside the Order_CancellationReason as a OrderCancellationReason1
func (t Order_CancellationReason) AsOrderCancellationReason1() (OrderCancellationReason1, error) {
	var body OrderCancellationReason1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrderCancellationReason1 overwrites any union data inside the Order_CancellationReason as the provided OrderCancellationReason1
func (t *Order_CancellationReason) FromOrderCancellationReason1(v OrderCancellationReason1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOrderCancellationReason1 performs a merge with any union data inside the Order_CancellationReason, using the provided OrderCancellationReason1
func (t *Order_CancellationReason) MergeOrderCancellationReason1(v OrderCancellationReason1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOrderCancellationReason2 returns the union data inside the Order_CancellationReason as a OrderCancellationReason2
func (t Order_CancellationReason) AsOrderCancellationReason2() (OrderCancellationReason2, error) {
	var body OrderCancellationReason2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrderCancellationReason2 overwrites any union data inside the Order_CancellationReason as the provided OrderCancellationReason2
func (t *Order_CancellationReason) FromOrderCancellationReason2(v OrderCancellationReason2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOrderCancellationReason2 performs a merge with any union data inside the Order_CancellationReason, using the provided OrderCancellationReason2
func (t *Order_CancellationReason) MergeOrderCancellationReason2(v OrderCancellationReason2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Order_CancellationReason) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Order_CancellationReason) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOrderResultOk returns the union data inside the OrderResult as a OrderResultOk
func (t OrderResult) AsOrderResultOk() (OrderResultOk, error) {
	var body OrderResultOk
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrderResultOk overwrites any union data inside the OrderResult as the provided OrderResultOk
func (t *OrderResult) FromOrderResultOk(v OrderResultOk) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"outcome":"ok"}`))
	t.union = b
	return err
}

// MergeOrderResultOk performs a merge with any union data inside the OrderResult, using the provided OrderResultOk
func (t *OrderResult) MergeOrderResultOk(v OrderResultOk) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"outcome":"ok"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOrderResultErr returns the union data inside the OrderResult as a OrderResultErr
func (t OrderResult) AsOrderResultErr() (OrderResultErr, error) {
	var body OrderResultErr
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrderResultErr overwrites any union data inside the OrderResult as the provided OrderResultErr
func (t *OrderResult) FromOrderResultErr(v OrderResultErr) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"outcome":"err"}`))
	t.union = b
	return err
}

// MergeOrderResultErr performs a merge with any union data inside the OrderResult, using the provided OrderResultErr
func (t *OrderResult) MergeOrderResultErr(v OrderResultErr) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"outcome":"err"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OrderResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"outcome"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t OrderResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "err":
		return t.AsOrderResultErr()
	case "ok":
		return t.AsOrderResultOk()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OrderResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OrderResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
